spring:
  profiles:
    active: dev

weather:
  service:
    api-key: 16f1d682ca8647a0b9b211336241206
    url: http://api.weatherapi.com/v1
    lang: ru
    days: 8

---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    locations: classpath:db/migration/h2
    baseline-on-migrate: true

  config:
    activate:
      on-profile: dev

---
spring:
  datasource:
    username: elaborate
    password: G_3mA@7F
    url: jdbc:postgresql://localhost:5432/skycast
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true

  config:
    activate:
      on-profile: prod