spring:
  datasource:
    generate-unique-name: false
    name: skycast

weather:
  service:
    api-key: 16f1d682ca8647a0b9b211336241206
    url: http://api.weatherapi.com/v1
    lang: ru
    days: 8