spring:
  datasource:
    generate-unique-name: false
    name: skycast

logging:
  level:
    root: INFO

weather:
  service:
    api-key: 59a483515dfa42b2b54122033241105
    url: http://api.weatherapi.com/v1